.\" -*- coding: utf-8-unix -*-
.\" groff -man -Tutf8 quickroute-gps.1
.\" Copyright © 2015 by Kristóf Ralovich
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" License.
.\"
.TH quickroute-gps 1 "2015-11" "quickroute-gps v2.4" "Route Analysis"
.SH "NAME"
quickroute-gps \- C# based GPS analysis software for getting your route on the map
.SH "SYNOPSIS"
.BI "quickroute-gps [ " "OPTIONS" " ] "
.SH DESCRIPTION
.B "quickroute-gps"
QuickRoute is a visual GPS analysis software for orienteering and
other outdoor activities. You can to display your route on a map, and
review split times and pace. It also allows direct upload of the
routes to a digital orienteering map archive (DOMA) or overlay it in
Google Earth.
.SH "OPTIONS"
.TP
\fB\<image file name>
Load the image given by the filename for analysis.
.SH HOW TO SUBMIT A BUG-REPORT
.PP
Please open a bug report at
.UR "https://github.com/ralovich/quickroute-linux/issues"
.BR "https://github.com/ralovich/quickroute-linux/issues"
.PP
In your report please include:
.LP
.RS
The log of the program in question (usually saved under ~/.config/QuickRoute/QuickRoute.log)?
.RE
.LP
.LP
.RS
What steps will reproduce the problem?
.RE
.LP
.LP
.RS
What is the expected output? What do you see instead?
.RE
.LP
.LP
.RS
What version of QuickRoute are you using? On what operating system? Is it pre-built of from sources?
.RE
.LP
.LP
.RS
What GPS are you trying to use? What firmware version?
.RE
.LP
.SH "AUTHOR"
.B quickroute-gps
was written by Mats Troeng <matstroeng@gmail.com>. Port to Linux/Mono
by Kristóf Ralovich <tade60@freemail.hu>. This man page is Copyright ©
2015 Kristóf Ralovich.
.SH "SEE ALSO"
.UR "https://github.com/ralovich/quickroute-linux"
.BR "https://github.com/ralovich/quickroute-linux"
.PP
.UR "http://www.matstroeng.se/quickroute/en"
.BR "http://www.matstroeng.se/quickroute/en"
.PP
.UR "http://o-training.net/blog/2011/04/13/gps-analysis-for-orienteering-the-basics"
.BR "http://o-training.net/blog/2011/04/13/gps-analysis-for-orienteering-the-basics"

