#!/bin/bash

# create tag for .deb package version
# git tag -a -m "debian/2.7-3" "debian/2.7-3" HEAD

# generate log file from git history
# git-dch --git-author --debian-branch=mono1 -v -N 2.7-3 --since=debian/2.7-2

ROOT=`mktemp -d --tmp=.`
eval ROOT=$ROOT

echo $ROOT
echo

./scripts/make-tarball
echo -e "\nTarball OK\n"

mv quickroute-gps*.tar.gz $ROOT/

( cd $ROOT;
    mkdir build;
    cd build
    tar -xzf ../quickroute-gps*.tar.gz
    echo -e "\nStarting to build...\n"
    debuild -eDISPLAY -us -uc && echo -e "\nBuild OK\ndeb package in '${ROOT}' \n";
)




