#!/bin/bash

ROOT=`mktemp -d --tmp=.`
eval ROOT=$ROOT

echo $ROOT
echo

./scripts/make-tarball
echo -e "\nTarball OK\n"

mv quickroute-gps*.tar.xz $ROOT/

( cd $ROOT;
    mkdir build;
    cd build
    tar --xz -xf ../quickroute-gps*.tar.xz
    echo -e "\nStarting to build...\n"
    debuild -us -uc && echo -e "\nBuild OK\ndeb package in '${ROOT}' \n";
)

