#!/bin/sh


#NUMBERS=`grep AssemblyInformationalVersion QuickRoute.UI/Properties/AssemblyInfo.cs | grep -o '[0-9]*'`
#echo $NUMBERS

A=`grep AssemblyInformationalVersion QuickRoute.UI/Properties/AssemblyInfo.cs | grep -o '[0-9]*' | head -1`
echo $A
B=`grep AssemblyInformationalVersion QuickRoute.UI/Properties/AssemblyInfo.cs | grep -o '[0-9]*' | head -2 | tail -1`
echo $B
C=`grep AssemblyInformationalVersion QuickRoute.UI/Properties/AssemblyInfo.cs | grep -o '[0-9]*' |  tail -1`
echo $C


VER=$A.$B
DEB_VER_MINOR=$C

git-dch --git-author --debian-branch=mono1 -vaN $VER-$DEB_VER_MINOR --distribution=experimental --debian-tag=experimental/%\(version\)s
