#!/bin/bash

VER=2.5
OUTNAME=quickroute-gps_${VER}.orig.tar.gz

FILES=`find . -type f -name \* -print | grep -v .git`
TMP_LIST=`mktemp`

#echo $FILES
#echo "TMP_LIST=${TMP_LIST}"
#echo ${FILES} > ${TMP_LIST}
#echo ${FILES} > dist-file-list

find . -type f -name \* -print | grep -v .git > scripts/dist-file-list

#tar -czvf ${OUTNAME} ${FILES}
