#!/bin/bash


A=`grep AssemblyInformationalVersion QuickRoute.UI/Properties/AssemblyInfo.cs | grep -o '[0-9]*' | head -1`
echo $A
B=`grep AssemblyInformationalVersion QuickRoute.UI/Properties/AssemblyInfo.cs | grep -o '[0-9]*' | head -2 | tail -1`
echo $B
C=`grep AssemblyInformationalVersion QuickRoute.UI/Properties/AssemblyInfo.cs | grep -o '[0-9]*' |  tail -1`
echo $C

VER=$A.$B

#VER=2.4
GIT_VER=`git log | head -1 | awk '{print $2 }'`
OUTNAME=quickroute-gps_${VER}.orig.tar

FILES=`find . -type f -name \* -print | grep -v .git`
TMP_LIST=`mktemp`

#echo $FILES
#echo "TMP_LIST=${TMP_LIST}"
#echo ${FILES} > ${TMP_LIST}
#echo ${FILES} > dist-file-list

#find . -type f -name \* -print | grep -v .git > scripts/dist-file-list

rm -fv ${OUTNAME}.gz ${OUTNAME}.xz
#tar -czvf ${OUTNAME}.gz -T scripts/origsrc-file-list
tar --xz -cf ${OUTNAME}.xz -T scripts/origsrc-file-list

echo ${OUTNAME}
