#!/bin/bash

VER=2.7
OUTNAME=quickroute-gps_${VER}.orig.tar

FILES=`find . -type f -name \* -print | grep -v .git`
TMP_LIST=`mktemp`

#echo $FILES
#echo "TMP_LIST=${TMP_LIST}"
#echo ${FILES} > ${TMP_LIST}
#echo ${FILES} > dist-file-list

#find . -type f -name \* -print | grep -v .git > scripts/dist-file-list

rm -fv ${OUTNAME}.gz ${OUTNAME}.xz
tar -czvf ${OUTNAME}.gz -T scripts/origsrc-file-list
tar --xz -cvf ${OUTNAME}.xz -T scripts/origsrc-file-list
